### ISSUE TITLE
BAT-P3 List Of Parameters

### ISSUE THREAD

**Issue by nuertey** [spaceinventor/libparam#3]
Hello @johandc,
Where can I locate the list of valid parameters for the BAT-P3 module? I am just getting familiar with the part by reading its datasheet, and I see a list of parameters retrieved with /bin/bash on page 9. That list is titled, **"Example telemetry using ‘satctl’ with CAN-dongle on a PC"**. 

I want to get at the description of these parameters and ideally look over their implementation in the available libparam source so that I can identify the types of the arguments as well. If these descriptions are in some document somewhere, that would do as well. Thank you.
Nuertey

**Comment by johandc** [comment]
The list is in the table on page 7.

**Comment by nuertey** [comment]
Thank you @johandc. I did see the table on page 7. However, I am puzzled that the parameters in that table only seem to be a subset of the actual parameter values shown retrieved in the list on page 9. Should I ignore the extra parameters--for example **ina_vbus** or **gndwdt**--shown retrieved on page 9? 

I have been tasked to write a module which amongst other things is responsible for exposing an API of the list of parameters for the BAT-P3 and its Aggregator to the user. I simply want to ensure that I have accounted for all possible parameters both write or strictly read. Thank you.

By the way, is the PCDU-12 what is considered the BAT-P3's 'Aggregator'? Thanks.

**Comment by johandc** [comment]
Yes you can safely ignore some of the many additional parameters. However we do have an additional set of parameters, which we call platform parameters. They are the same on all subsystems, and relate to bootloader, CSP and then there's the ground watchdog. We have description of those in a separate document, as we don't like to repeat them in all datahseets.

Please contact me on my email, for further support. As this big tracker is public.

The PCDU is not the Aggregator module.
