### ISSUE TITLE
When using PARAM_DEFINE_* macros in C++, get "designator order does not match declaration order"

### ISSUE THREAD

**Issue by negatratoron** [spaceinventor/libparam#7]
Compiler: g++ 11.3.0

Expected behavior: `PARAM_DEFINE_*` macros generate compiling C++ code.

Actual behavior: The compile fails with the error:

```
param.h:199:9: error: designator order for field ‘param_s::id’ does not match declaration order in ‘param_t’ {aka ‘param_s’}
```

This appears to be because in C++20, the order of designated initializers has to match the declaration order.  See:

> Note: out-of-order designated initialization, nested designated initialization, mixing of designated initializers and regular initializers, and designated initialization of arrays are all supported in the [C programming language](https://en.cppreference.com/w/c/language/struct_initialization), but are not allowed in C++.

From https://en.cppreference.com/w/cpp/language/aggregate_initialization#Designated_initializers

It seems like this can be fixed just by re-ordering the initializers and inserting NULL initializers as needed in the `PARAM_DEFINE_*` macros.

---

Reproducible example: In a new project directory:

Clone libcsp into lib/csp and libparam into lib/param (as done here: https://github.com/spaceinventor/csh)

meson.build file:
```
project('TestProgram',
	'cpp',
	subproject_dir: 'lib'
)

csp_dep = dependency('csp', fallback: ['csp', 'csp_dep'], required: true)
param_dep = dependency('param', fallback: ['param', 'param_dep'], required: true)

main = executable(
	'main',
	[ 'src/main.cpp' ],
	dependencies: [csp_dep, param_dep]
)
```

src/main.cpp file:
```
#include <param/param.h>

static uint8_t _ch_on[12];
PARAM_DEFINE_REMOTE_DYNAMIC(20, ch_on, 3, PARAM_TYPE_UINT8, 12, 0, PM_CONF, &_ch_on, "");

int main() {
  return 0;
}
```

**Comment by johandc** [comment]
I see.

Can you propose a fix, inserting the NULL's and fixing the order? I dont have the C++ compiler readily availabe to make the fix quickly.

**Comment by negatratoron** [comment]
Oh hey, yes I can

**Comment by nuertey** [comment]
Great guys that you all are designing things nicely and bulletproofing the great code further. @negatratoron @johandc These days I am working for Blue Origin, and writing equally good code for their Lunar Lander program. I am happy to keep abrest of your efforts still. Good job!

Regards
Nuertey
